"""adicionar relationship itens a pedidos

Revision ID: 10c2e87ffb14
Revises: a5ccdb96de11
Create Date: 2026-03-06 18:58:29.672028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c2e87ffb14'
down_revision: Union[str, Sequence[str], None] = 'a5ccdb96de11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
