"""removendo ativo

Revision ID: 228c4fe6ba07
Revises: 861d3fa9c628
Create Date: 2026-02-17 12:12:12.020321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228c4fe6ba07'
down_revision: Union[str, Sequence[str], None] = '861d3fa9c628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ativo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ativo', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
