"""initial

Revision ID: 6298b7732d17
Revises: 
Create Date: 2026-03-16 19:21:42.258039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6298b7732d17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoriaaddons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoriaprodutos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idcategora', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('preco_addon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['idcategora'], ['categoriaaddons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idusuario', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['idusuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('idcategoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idcategoria'], ['categoriaprodutos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtosvariantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idproduto', sa.Integer(), nullable=True),
    sa.Column('variacao', sa.String(), nullable=True),
    sa.Column('preco_variante', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['idproduto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idpedido', sa.Integer(), nullable=True),
    sa.Column('idprodutovariante', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['idpedido'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['idprodutovariante'], ['produtosvariantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itensaddons ',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idaddon', sa.Integer(), nullable=True),
    sa.Column('iditempedido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idaddon'], ['addons.id'], ),
    sa.ForeignKeyConstraint(['iditempedido'], ['itens_pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itensaddons ')
    op.drop_table('itens_pedidos')
    op.drop_table('produtosvariantes')
    op.drop_table('produtos')
    op.drop_table('pedidos')
    op.drop_table('addons')
    op.drop_table('usuarios')
    op.drop_table('categoriaprodutos')
    op.drop_table('categoriaaddons')
    # ### end Alembic commands ###
